name: cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    s3_sync:
        name: AWS S3 Sync
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::590184031400:role/github-action
                aws-region: ap-northeast-2

            - name: Upload static files
              run:  aws s3 sync static_files s3://terraform-study-s3-bucket 
                    --region ap-northeast-2 
        
    update_ecs:
        name: Update ECS
        runs-on: ubuntu-latest
        needs: s3_sync
        permissions:
            id-token: write
            contents: read
                    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
                    
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::590184031400:role/github-action-ecr
                aws-region: ap-northeast-2
                    
            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              
            - name: build and push to ECR
              uses: docker/build-push-action@v5
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: skkudinginfra
              with:
                file: docker/dockerfile
                context: docker
                push: true
                tags: ${{ steps.login-ecr.outputs.registry }}/skkudinginfra:latest

              
                    



